/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "loginSellerAccountFunction",
            "endpoint": "https://pzvpd6xqdh.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "openSellerAccount",
            "endpoint": "https://ftzq7wjyef.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "loginBuyerAccountFunction",
            "endpoint": "https://5e1oyazlof.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "openBuyerAccount",
            "endpoint": "https://zenehpt22h.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "sellerReviewItems",
            "endpoint": "https://hoobnngov9.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "sellerUnpublishItem",
            "endpoint": "https://hzob7hmuph.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "SellerEditItemFunction",
            "endpoint": "https://qbylae5by7.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "SellerPublishItemFunction",
            "endpoint": "https://t033iv5klk.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "customerReviewItems",
            "endpoint": "https://6haebl2d68.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "addItem",
            "endpoint": "https://1tlepvbqtd.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "sellerremoveInactiveItem",
            "endpoint": "https://dezgzbir75.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "loginAdminAccount",
            "endpoint": "https://h25ni7mf84.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "buyerAddFunds",
            "endpoint": "https://3o946p6awf.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "buyerGetFunds",
            "endpoint": "https://c649hbuiu7.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "buyerPlaceBid",
            "endpoint": "https://0x670tndh9.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "buyerViewItem",
            "endpoint": "https://d4judgu50g.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "buyerViewItems",
            "endpoint": "https://tq89ogqnr2.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "sellerCloseAccount",
            "endpoint": "https://i7n2snzpg5.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "sellerViewItem",
            "endpoint": "https://lpr8qgd76a.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "sellerRequestUnfreezeItem",
            "endpoint": "https://b59dq9imok.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "sellerArchiveItem",
            "endpoint": "https://w35nmm676d.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "sellerFulfillItem",
            "endpoint": "https://sj88qivm8j.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "buyerViewRecentlySold",
            "endpoint": "https://ezygj3fb3j.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "buyerViewActiveBids",
            "endpoint": "https://uynxrlmukd.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "buyerReviewPurchases",
            "endpoint": "https://zn9hxjy5a7.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "adminFreezeItem",
            "endpoint": "https://0v4aeo66se.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "adminGenerateAuctionReport",
            "endpoint": "https://7ttxb2kws7.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "adminGenerateForensicsReport",
            "endpoint": "https://fhe5bsrfch.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "buyerCloseAccount",
            "endpoint": "https://df4xgq609l.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "sellerBuyerNow",
            "endpoint": "https://5jd0tanpxi.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "buyerBuyNow",
            "endpoint": "https://jpohewry18.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:56fb1efe-48b3-4e9f-a5de-b2c801ec0705",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_l0tPGNdNV",
    "aws_user_pools_web_client_id": "6an160j16m6a09hdvo898m9a5h",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "auctionhousec0fa4b6d5a2641a187df78aa6945b28f5f64c-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
